### ISSUE TITLE
NTType: Construrtor

### ISSUE THREAD

**Issue by emcardoso** [lives-group/APEG#1]
Remover a funão ADD do NTTye, e fazer com que todos os parâmetros sejam rcebidos pelo construtor.

**Comment by deisekelley** [comment]
Detectamos que o FormalVisitor também não está bom. 
Ele deveria servir de base para construir visitors com menos código boilerplate.

**Comment by deisekelley** [comment]
Building visitor agora extende FormalVisitor, isso reduziu o tamanho da classe, eliminando código boilerplate. O construtor de NTType foi modificaod para a forma solicitada. As tabelas  forma movidas para um pacote próprio (Environmtes) dentro de apeg.parser.ast.visitors.  O Building visistor foi renomeado para BuldEnvironmentVisitor. A tabela de símbolos RuleEnvironment apenas mapeia noes de não terminais para símbolos.

**Comment by leovieira** [comment]
Na classe NTType, a função match deve ir para o visitor que realiza a veriicação de tipos.
Deve-se implementar funções getParamAt(int i) e getReturnAt(i) que obtém o tipo posicional e funções get para obter informações da aridade da função (não-terminal).

**Comment by emcardoso** [comment]
This is done.
