### ISSUE TITLE
teste falho no metaGrammar 

### ISSUE THREAD

**Issue by DeiversonMAP** [lives-group/APEG#33]
TestExprs.MetaRuleTest01:844 expected: <([ (metaRule 'foobar' ([ 'int 'map 'string]) ([ 'x' 'm' 'str']))])> but was: <apeg.ast.expr.MetaGrammar@1b266842>

começou a falhar no dia 17/09/21 depois da adição do nodo Grammar

**Comment by tassilucas** [comment]
Olá Deiverson, 

Creio que 487b561fb3bfa69ded3a980b5c29ff764d93147d deve consertar esse problema.

Obrigado.
