### ISSUE TITLE
Precedence error (Not and Opcional)

### ISSUE THREAD

**Issue by DeiversonMAP** [lives-group/APEG#35]
The following PEG expression in TestPeg.java ,  it isn't working because of the precedence level of the Not expression and Opcional expression :
![image](https://user-images.githubusercontent.com/73710805/136442336-a0a6449d-9d25-4a3a-a4c3-e925a6453f78.png)

**Comment by tassilucas** [comment]
Hey Deiverson,

I think 43b8495 fixed this problem.

Thanks.
