### ISSUE TITLE
Precendence and associativity of operators.

### ISSUE THREAD

**Issue by emcardoso** [lives-group/APEG#6]
Guys (and Girls),
I Think there is something wrong with the precedence and associativity of operators.
The expression `x < y || z == 2` was reporting an error on the type system. At first i thought it was an erro in the type checker, but then I notice that the stack or this specific example was (from botton to top) boolean, int and the error war reported at the OR operator. I guess that the parser is interpreting the sentence as `((x<y) || z) == 2` . Changing the parenthesis to `x < y || (z == 2)` the type system checks correctly.  Is this the intended syntax ?

**Comment by lvsreis** [comment]
You were right. The precedence was wrong. I've corrected this issue.
