### ISSUE TITLE
Maven Building reveals problem !

### ISSUE THREAD

**Issue by emcardoso** [lives-group/APEG#8]
Ah Guys,
I think the maven building found a problem. It is actually very weird !
When I first run the mvn compile i got this: 
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project apeg: Compilation failure: Compilation failure: 
[ERROR] /home/elton/devel/ProjetoAPEG/APEG/language/code/compiler/src/main/java/apeg/parse/ast/OrExprNode.java:[5,32] error: cannot find symbol
[ERROR]  class LogicalBinExpr
[ERROR] /home/elton/devel/ProjetoAPEG/APEG/language/code/compiler/src/main/java/apeg/parse/ast/AndExprNode.java:[5,33] error: cannot find symbol
[ERROR]  class LogicalBinExpr
[ERROR] /home/elton/devel/ProjetoAPEG/APEG/language/code/compiler/src/main/java/apeg/parse/ast/visitor/VerifyVisitor.java:[116,28] error: cannot find symbol` 
So i though that the problem was the superclass of the (And,Or)ExprNode LogicalBinExpr
So i Notice the superclass is missing !
Since I pull this from git, I wounder, how is the Deise's code compiling on Eclipse ?
Leo, any suggestions on this ? Should I create the class LogicalBinExpr ?

**Comment by deisekelley** [comment]
Hi Elton, i saw that the class LogicalBinExpr isn`t in the index... i will make the commit now

**Comment by deisekelley** [comment]
done.

**Comment by deisekelley** [comment]
hahaa ok, make the magic!
